config/routes.rb
Rails.application.routes.draw do
  resources :contact_messages, only: [:create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "searches#new"

  resources :receipts

  get 'baskets/show'
  resources :products do
    member do
      get :subcategories
      get :districts
      get :states
      get :sectors
      get :marinas
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :profiles
  resources :order_items
  resources :searches
  resource :baskets, only: [:show]
  devise_for :users, controllers: { registrations: "registrations" }

  get '/profile',to: 'pages#dashboard'
  get '/locations',to: 'pages#locations'
  get '/about_us',to: 'pages#about_us'
  get '/contact_us',to: 'pages#contact'
  get '/your_products', to: 'pages#your_products'
  get '/your_clients', to: 'pages#your_clients'
  get '/bocas_del_toro', to: 'pages#bocas_del_toro'
  get '/cocle', to: 'pages#cocle'
  get '/colon', to: 'pages#colon'
  get '/chiriqui', to: 'pages#chiriqui'
  get '/darien', to: 'pages#darien'
  get '/herrera', to: 'pages#herrera'
  get '/los_santos', to: 'pages#los_santos'
  get '/panama', to: 'pages#panama'
  get '/veraguas', to: 'pages#veraguas'
  get '/panama_oeste', to: 'pages#panama_oeste'
  get '/embera', to: 'pages#embera'
  get '/guna_yala', to: 'pages#guna_yala'
  get '/paguelofacil_test', to: 'pages#paguelofacil_test'
  get '/payment_method', to: 'receipts#payment_method'
  get '/check_out', to: 'receipts#payment_confirmation'
  get '/card_error', to: 'pages#card_error'
  get '/thank_you', to: 'pages#thank_you'
  get '/contact', to: 'contact_messages#contact'

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  validates :nombre_completo, presence: true
  validates :telefono, presence: true
  validates :fecha_de_nacimiento, presence: true
  validates :nacionalidad, presence: true
end

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-md-8">
         <%= f.input :nombre_completo %>
      </div>
      <div class="col-md-4">
        <%= f.input :telefono %>
      </div>
    </div>
    <div class="row">
      <%= f.input :photo, as: :file %>
    </div>
    <div class="row">
      <div class="col-md-4">
         <%= f.input :nacionalidad, :collection => @countries %>
      </div>
      <div class="col-md-4">
        <%= f.input :fecha_de_nacimiento, start_year: Time.now.year - 18, end_year: Time.now.year - 100, order: %i(day month year) %>
      </div>
    </div>
  </div>
  <hr>
  <div class="form-actions">
    <%= f.button :submit, 'Guardar Perfil', class: 'btn btn-boat' %>
  </div>
<% end %>

app/views/profiles/_profile.html.erb
<div id="<%= dom_id profile %>">
  <p>
    <strong>Nombre completo:</strong>
    <%= profile.nombre_completo %>
  </p>

  <p>
    <strong>Fecha de nacimiento:</strong>
    <%= profile.fecha_de_nacimiento %>
  </p>

  <p>
    <strong>Nacionalidad:</strong>
    <%= profile.nacionalidad %>
  </p>

  <p>
    <strong>Experiencia:</strong>
    <%= profile.experiencia %>
  </p>

  <p>
    <strong>Teléfono:</strong>
    <%= profile.telefono %>
  </p>

  <p>
    <strong>Nombre emergencia:</strong>
    <%= profile.nombre_emergencia %>
  </p>

  <p>
    <strong>Telefono emergencia:</strong>
    <%= profile.telefono_emergencia %>
  </p>

  <p>
    <strong>User:</strong>
    <%= profile.user_id %>
  </p>

</div>

app/views/profiles/edit.html.erb
<% if current_user.profile.id == @profile.id%>
<br>
<br>
<br>
<div class="container" style="">
  <div style="background-color: white; padding: 30px;  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
    <br>
    <h2 style="font-family: 'IM Fell DW Pica SC', serif;"><i class="fas fa-user" style="color: #2078AD !important;"></i> Registro de Perfil</h2>
    <hr>
    <%= render "form", profile: @profile %>

    <br>

    <div>
      <%= link_to "Show this profile", @profile %> |
      <%= link_to "Back to profiles", profiles_path %>
    </div>
    <% end %>
    <br>
    <hr>
  </div>
</div>
<br>
<br>
<br>

app/views/profiles/index.html.erb
<h1>Profiles</h1>

<div id="profiles">
  <% @profiles.each do |profile| %>
    <%= render profile %>
    <p>
      <%= link_to "Show this profile", profile %>
    </p>
  <% end %>
</div>

<%= link_to "New profile", new_profile_path %>

app/views/profiles/new.html.erb
<br>
<br>
<br>
<div class="container" style="">
  <div style="background-color: white; padding: 30px;  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
    <br>
    <h2 style="font-family: 'IM Fell DW Pica SC', serif;"><i class="fas fa-user" style="color: #2078AD !important;"></i> Registro de Perfil</h2>
    <hr>
    <%= render "form", profile: @profile %>


    <br>
  </div>
</div>
<br>
<br>
<br>

app/views/profiles/show.html.erb
<br>
<br>
<br>
<br>
<div>
  <div class="container">
    <div style="background-color: white; padding: 30px;  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
      <br>
      <h2 style="font-family: 'IM Fell DW Pica SC', serif"><i class="fas fa-user"  style="color: #2078AD;"></i> PERFIL DE USUARIO</h2>
      <hr>
      <br>
      <div class="text-center">
       <% if  @profile %>
       <% if @profile.photo.attached? %>
        <%= cl_image_tag @profile.photo.key, height: 500, width: 500, crop: :fill, class: "avatar-profile" %>
        <% else %>
        <%= image_tag("user-boat.png", height: 200)%>
        <% end %>

       <br>
       <br>
       <p><i class="fas fa-user"></i> Nombre de Usuario: <%= @profile.nombre_completo %></p>
       <p><i class="fas fa-flag"></i> Nacionalidad : <%= @profile.nacionalidad %></p>
       <p><i class="fas fa-calendar"></i> Año: <%= @profile.fecha_de_nacimiento %></p>
       <%if current_user.id == @profile.id%>
       <i class="fas fa-pencil"></i> <%= link_to "Editar", edit_profile_path(@profile)%>
       <% end %>
       <br>

      <hr>
      <br>
      <br>
      <% else %>
      <%= image_tag("user-boat.png", height: 200)%>
      <br>
      <a class="btn btn-boat" href="/profiles/new"><i class="fas fa-user"></i> Registrar Perfil</a>

      <br>

      <br>

      <hr>
      <br>
      <br>
    </div>
    <%end%>
  </div>
</div>
</div>
<br>
<br>