config/routes.rb
Rails.application.routes.draw do
  resources :contact_messages, only: [:create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "searches#new"

  resources :receipts

  get 'baskets/show'
  resources :products do
    member do
      get :subcategories
      get :districts
      get :states
      get :sectors
      get :marinas
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :profiles
  resources :order_items
  resources :searches
  resource :baskets, only: [:show]
  devise_for :users, controllers: { registrations: "registrations" }

  get '/profile',to: 'pages#dashboard'
  get '/locations',to: 'pages#locations'
  get '/about_us',to: 'pages#about_us'
  get '/contact_us',to: 'pages#contact'
  get '/your_products', to: 'pages#your_products'
  get '/your_clients', to: 'pages#your_clients'
  get '/bocas_del_toro', to: 'pages#bocas_del_toro'
  get '/cocle', to: 'pages#cocle'
  get '/colon', to: 'pages#colon'
  get '/chiriqui', to: 'pages#chiriqui'
  get '/darien', to: 'pages#darien'
  get '/herrera', to: 'pages#herrera'
  get '/los_santos', to: 'pages#los_santos'
  get '/panama', to: 'pages#panama'
  get '/veraguas', to: 'pages#veraguas'
  get '/panama_oeste', to: 'pages#panama_oeste'
  get '/embera', to: 'pages#embera'
  get '/guna_yala', to: 'pages#guna_yala'
  get '/paguelofacil_test', to: 'pages#paguelofacil_test'
  get '/payment_method', to: 'receipts#payment_method'
  get '/check_out', to: 'receipts#payment_confirmation'
  get '/card_error', to: 'pages#card_error'
  get '/thank_you', to: 'pages#thank_you'
  get '/contact', to: 'contact_messages#contact'

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/contact_message.rb
class ContactMessage < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true
  validates :phone, presence: true
end

app/controllers/contact_messages_controller.rb
class ContactMessagesController < ApplicationController
  before_action :set_contact_message, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user!, only: [:new, :create, :contact]

  # GET /contact_messages or /contact_messages.json
  def index
    @contact_messages = ContactMessage.all
  end

  # GET /contact_messages/1 or /contact_messages/1.json
  def show
  end

  # GET /contact_messages/new
  def new
    @contact_message = ContactMessage.new
  end

  def contact
    @contact_message = ContactMessage.new
  end

  # GET /contact_messages/1/edit
  def edit
    @contact_message = ContactMessage.new
  end

  # POST /contact_messages or /contact_messages.json
  def create
    @contact_message = ContactMessage.new(contact_message_params)

    respond_to do |format|
      if @contact_message.save
        format.html { redirect_to contact_path, notice: "Contact message was successfully sent." }
        format.json { render :show, status: :created, location: @contact_message }
      else
        format.html { render :contact, status: :unprocessable_entity }
        format.json { render json: @contact_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_messages/1 or /contact_messages/1.json
  def update
    respond_to do |format|
      if @contact_message.update(contact_message_params)
        format.html { redirect_to contact_message_url(@contact_message), notice: "Contact message was successfully updated." }
        format.json { render :show, status: :ok, location: @contact_message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_messages/1 or /contact_messages/1.json
  def destroy
    @contact_message.destroy

    respond_to do |format|
      format.html { redirect_to contact_messages_url, notice: "Contact message was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_message
      @contact_message = ContactMessage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_message_params
      params.require(:contact_message).permit(:name, :email, :phone, :message)
    end
end

app/views/contact_messages/_contact_message.html.erb
<div id="<%= dom_id contact_message %>">
  <p>
    <strong>Name:</strong>
    <%= contact_message.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= contact_message.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= contact_message.phone %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= contact_message.message %>
  </p>

</div>

app/views/contact_messages/_form.html.erb
<%= simple_form_for(@contact_message) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :phone %>
    <%= f.input :message %>
  </div>
<br>
  <div class="form-actions">
    <%= f.button :submit, 'Enviar', class:'btn btn-boat' %>
  </div>
<% end %>

app/views/contact_messages/contact.html.erb
<div style="background-color: ; padding-top: 100px;">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div style="">
          <h1 style="margin-bottom: 0; font-family: 'IM Fell DW Pica SC', serif; color: #2078AD; font-size: 50px"> Contactanos</h1>
          <br>
          <p><i class="fas fa-phone" style="color: #2078AD;"></i> +65 62230037 <br>
            <br>
            <i class="fas fa-envelope" style="color: #2078AD;"></i> contact@theartling.com <br>
            <br>
            <i class="fas fa-map-marker-alt" style="color: #2078AD;"></i> Singapore <br>

            91B Tanjong Pagar Road <br>
            Singapore 088512 <br>

            Office Hours: Mon-Fri 1000 - 1700 <br>
            <br>
            <i class="fas fa-map-marker-alt" style="color: #2078AD;"></i>  Shanghai <br>

            1F, Building 31, No. 322 <br>
            Jiaozhou Road, Shanghai <br>

          By Appointment Only</p>
          <br>
          <br>
        </div>
      </div>
      <div class="col-md-8">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d12088.901455905436!2d-73.98040158273815!3d40.75706775823158!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c258f97bdb102b%3A0xea9f8fc0b3ffff55!2sThe%20Museum%20of%20Modern%20Art!5e0!3m2!1sen!2spa!4v1650350147928!5m2!1sen!2spa" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
      </div>
    </div>
    <br>
    <br>
    <br>
  </div>
  <div class="container">
   <div style="background-color: white; padding: 30px;  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
     <div class="text-center">
      <h1 style="font-family: 'IM Fell DW Pica SC', serif; color: #2078AD;">Dejanos un mensaje</h1>

    </div>

    <%= render "form", contact_message: @contact_message %>
      </div>
    </div>
  </div>
  <br>
  <br>

app/views/contact_messages/edit.html.erb
<h1>Editing contact message</h1>

<%= render "form", contact_message: @contact_message %>

<br>

<div>
  <%= link_to "Show this contact message", @contact_message %> |
  <%= link_to "Back to contact messages", contact_messages_path %>
</div>

app/views/contact_messages/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contact messages</h1>

<div id="contact_messages">
  <% @contact_messages.each do |contact_message| %>
    <%= render contact_message %>
    <p>
      <%= link_to "Show this contact message", contact_message %>
    </p>
  <% end %>
</div>

<%= link_to "New contact message", new_contact_message_path %>

app/views/contact_messages/new.html.erb
<h1>New contact message</h1>

<%= render "form", contact_message: @contact_message %>

<br>

<div>
  <%= link_to "Back to contact messages", contact_messages_path %>
</div>

app/views/contact_messages/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contact_message %>

<div>
  <%= link_to "Edit this contact message", edit_contact_message_path(@contact_message) %> |
  <%= link_to "Back to contact messages", contact_messages_path %>

  <%= button_to "Destroy this contact message", @contact_message, method: :delete %>
</div>