config/routes.rb
Rails.application.routes.draw do
  resources :contact_messages, only: [:create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "searches#new"

  resources :receipts

  get 'baskets/show'
  resources :products do
    member do
      get :subcategories
      get :districts
      get :states
      get :sectors
      get :marinas
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :profiles
  resources :order_items
  resources :searches
  resource :baskets, only: [:show]
  devise_for :users, controllers: { registrations: "registrations" }

  get '/profile',to: 'pages#dashboard'
  get '/locations',to: 'pages#locations'
  get '/about_us',to: 'pages#about_us'
  get '/contact_us',to: 'pages#contact'
  get '/your_products', to: 'pages#your_products'
  get '/your_clients', to: 'pages#your_clients'
  get '/bocas_del_toro', to: 'pages#bocas_del_toro'
  get '/cocle', to: 'pages#cocle'
  get '/colon', to: 'pages#colon'
  get '/chiriqui', to: 'pages#chiriqui'
  get '/darien', to: 'pages#darien'
  get '/herrera', to: 'pages#herrera'
  get '/los_santos', to: 'pages#los_santos'
  get '/panama', to: 'pages#panama'
  get '/veraguas', to: 'pages#veraguas'
  get '/panama_oeste', to: 'pages#panama_oeste'
  get '/embera', to: 'pages#embera'
  get '/guna_yala', to: 'pages#guna_yala'
  get '/paguelofacil_test', to: 'pages#paguelofacil_test'
  get '/payment_method', to: 'receipts#payment_method'
  get '/check_out', to: 'receipts#payment_confirmation'
  get '/card_error', to: 'pages#card_error'
  get '/thank_you', to: 'pages#thank_you'
  get '/contact', to: 'contact_messages#contact'

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :order_items
  has_many :receipt_items
  has_many_attached :photos
  validates :categoria, presence: true
  validates :subcategoria, presence: true
  validates :titulo, presence: true
  validates :precio, presence: true
  validates :descripcion, presence: true
  validates :provincia, presence: true
  validates :distrito, presence: true
  validates :photos, presence: true, on: :create


  def self.search(search)
    if search
      where(["provincia LIKE ?","%#{search}%"])
    else
      all
    end
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  skip_before_action :authenticate_user!, only: [ :subcategories, :districts, :states ]
  # GET /products or /products.json
  def index
    @products = Product.search(params[:search])
    @search = Search.new
    @categories = Category.all.pluck(:title)
    @provinces = Province.all.pluck(:title)
  end

  # GET /products/1 or /products/1.json
  def show
     if @product.activacion === 'Activo' and @product.estatus === 'Valido'
      @order_item = current_order.order_items.new
      @order_items = current_order.order_items
    elsif current_user == @product.user
      @order_item = current_order.order_items.new
       @order_items = current_order.order_items
    elsif current_user and current_user.admin
       @order_item = current_order.order_items.new
       @order_items = current_order.order_items
    else
      redirect_to root_path
    end
  end

  # GET /products/new
  def new
   if current_user.profile
    @product = Product.new
    @categories = Category.all.pluck(:title)
    @provinces = Province.all.pluck(:title)
  else
    redirect_to '/profiles/new'
    end
  end

  # GET /products/1/edit
  def edit
    if current_user == @product.user or current_user.admin
      @categories = Category.all.pluck(:title)
      @provinces = Province.all.pluck(:title)

    else
      redirect_to root_path
    end
  end

  # POST /products or /products.json
  def create
    if current_user
      @product = Product.new(product_params)
      @product.user = current_user
      @product.estatus = 'Nuevo'
      respond_to do |format|
        if @product.save
          ProductMailer.with(product: @product).new_product_email.deliver_later
          format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
          format.json { render :show, status: :created, location: @product }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
def update
  puts product_params[:photos]
  if product_params[:photos].blank? or product_params[:photos] === [""]
    puts 'blank---------------------------'
    if current_user == @product.user || current_user.admin
    respond_to do |format|
      if product_params[:photos].nil? || product_params[:photos].empty?
        # Remove the line that updates the attributes directly
        if @product.update(product_params.except(:photos, :photos_destroy))
          format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { render :edit }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      else
        # Only remove the photos if the `photos_destroy` parameter is present and set to "1"
        should_remove_photos = product_params[:photos_destroy] == "1"
        if should_remove_photos
          @product.photos.purge
        end

        @product.assign_attributes(product_params.except(:photos, :photos_destroy))

        # Attach the new photos
        @product.photos.attach(product_params[:photos])

        if @product.save
          format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
          format.json { render :show, status: :ok, location: @product }
        else
          format.html { render :edit }
          format.json { render json: @product.errors, status: :unprocessable_entity }
        end
      end
    end
  else
    redirect_to root_path
  end
  else
    puts 'data---------------------------'
    if current_user == @product.user || current_user.admin
      respond_to do |format|
        if product_params[:photos].nil?
          # Remove the line that updates the attributes directly
          if @product.update(product_params.except(:photos, :photos_destroy))
            format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
            format.json { render :show, status: :ok, location: @product }
          else
            format.html { render :edit }
            format.json { render json: @product.errors, status: :unprocessable_entity }
          end
        else
          # Remove the existing photos before attaching new ones only if new photos are present
          if product_params[:photos].present?
            @product.photos.purge
          end

          @product.assign_attributes(product_params.except(:photos, :photos_destroy))

          # Attach the new photos
          @product.photos.attach(product_params[:photos])

          # Save the product to trigger validations
          if @product.save
            format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
            format.json { render :show, status: :ok, location: @product }
          else
            format.html { render :edit }
            format.json { render json: @product.errors, status: :unprocessable_entity }
          end
        end
      end
    else
      redirect_to root_path
    end
  end
end

  # DELETE /products/1 or /products/1.json
  def destroy
    if current_user == @product.user
      @product.destroy

      respond_to do |format|
        format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      redirect_to root_path
    end
  end

   def subcategories
    # @target = params[:target]
    subcategories = Subcategory.joins(:category).where("categories.title LIKE ?", "%#{params[:id]}%").pluck(:name)
    render json: { value:  subcategories}, status: 200
  end

  def districts
    districts = District.joins(:province).where("provinces.title LIKE ?", "%#{params[:id]}%").pluck(:name)
    render json: { value:  districts}, status: 200
  end

  def states
    states = State.joins(:district).where("districts.name LIKE ?", "%#{params[:id]}%").pluck(:name)
    render json: { value:  states}, status: 200
  end

  def sectors
    sectors = Sector.joins(:state).where("states.name LIKE ?", "%#{params[:id]}%").pluck(:name)
    render json: { value:  sectors}, status: 200
  end

  def marinas
    bays = Bay.joins(:sector).where("sectors.name LIKE ?", "%#{params[:id]}%").pluck(:name)
    render json: { value:  bays}, status: 200
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:titulo, :categoria, :subcategoria, :provincia, :distrito, :corregimiento, :sector, :marina, :precio, :descripcion, :user_id,:activacion, :estatus, :direccion, photos: [])
    end
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
<% if @product.errors.any? %>
<div class="alert alert-danger">
  <ul>
    <% @product.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div>
  <div class="mb-3">
    <%= f.label :categoria, 'Categoria *',class: "form-label" %>
    <%= f.select :categoria, @categories, { prompt: "Select a category" }, { class: "form-select", required: true, id: "categories", onChange:"handleChange('subcategories', 'sub_categories', 'categories')"} %>
  </div>
  <div class="mb-3">
    <%= f.label :subcategoria, 'Subcategoria *', class: "form-label" %>
    <%= f.select :subcategoria,[], {prompt: "Select a subcategory"}, { id: "sub_categories",  required: true, class: "form-select" }%>
  </div>
</div>
<div class="row">
  <div class="col-md-8">
    <%= f.label :titulo, 'Titulo *',  class: "form-label" %>
    <%= f.text_field :titulo, { required: true, class: "form-control"  } %>
  </div>
  <div class="col-md-2">
    <%= f.label :precio, 'Precio *', class: "form-label" %>
    <%= f.number_field :precio, { required: true, class: "form-control", placeholder: "0.00"  } %>
  </div>
  <div class="col-md-2">
    <%= f.label :activacion, 'Activar *',  class: "form-label" %>
    <%= f.select :activacion, ['Activo', 'Desactivo'], { prompt: "" }, { required: true, class: "form-select"  } %>
  </div>
</div>
<br>
<div class="row">
  <div class="mb-3">
    <%= f.label :descripcion, 'Descripcion *', class: "form-label" %>
    <%= f.text_area :descripcion, class: "form-control" %>
  </div>
</div>
<div >
  <div class="mb-3">
    <%= f.label :provincia, 'Provincia *',  class: "form-label" %>
    <%= f.select :provincia, @provinces,  { prompt: "Select a province" },{ class: "form-select",required: true, id: "province",  onChange:"handleChange('districts', 'district', 'province')"} %>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    <%= f.label :distrito, 'Distrito *',  class: "form-label" %>
    <%= f.select :distrito, [],  { prompt: "Select a district" }, { class: "form-select",required: true, id: "district",  onChange:"handleChange('states', 'corregimiento', 'district')" } %>
  </div>
  <div class="col-md-4">
    <%= f.label :corregimiento, 'Corregimiento *',  class: "form-label" %>
    <%= f.select :corregimiento, [],  { prompt: "Select a corregimiento" }, { class: "form-select", id: "corregimiento", required: true, onChange:"handleChange('sectors', 'sector', 'corregimiento')" } %>
  </div>
  <div class="col-md-4">
    <% marinas_panama = ["Balboa Yacht Club - Ciudad de Panamá","Flamenco Marina - Isla Flamenco, Ciudad de Panamá","Shelter Bay Marina - Colón","Vista Mar Marina - San Carlos","Red Frog Beach Marina - Isla Bastimentos, Bocas del Toro","Marina Puerto Lindo - Puerto Lindo, Colón","Marina del Rey - Isla Linton, Bocas del Toro","Marina de la Playita - Ciudad de Panamá","Marina Corotú - David, Chiriquí","Marina Vista Mar - San Carlos","Marina Panamar - Ciudad de Panamá","Marina La Playita - Taboga, Ciudad de Panamá","Marina Cacique - Isla Iguana, Veraguas","Marina La Puntilla - Ciudad de Panamá","Marina de Chiriquí - Boca Chica, Chiriquí","Marina Puerto Azul - Isla Contadora, Archipiélago de Las Perlas","Marina de Pedasí - Pedasí, Los Santos","Marina Puerto Bahía - Punta Chame, Panamá Oeste","Marina Vista Mar - San Carlos","Marina El Capitán - Chame, Panamá Oeste"] %>
    <%= f.label :marina, 'Marina *',  class: "form-label" %>
    <%= f.select :marina, marinas_panama,  { prompt: "Select a marina" }, { class: "form-select", id: "marina" } %>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <%= f.label :direccion, 'Direccion *',  class: "form-label" %>
    <%= f.text_field :direccion, prompt: "Ejemplo: Calle 8 Este, Casa #15B", required: true, class: "form-control" %>
  </div>
</div>
<br>
<div class="row">
  <div class="col">
    <%= f.label :photos, 'Imagenes *',  class: "form-label" %>
    <%= f.file_field :photos,{  multiple: true, class: 'form-control file', required: true } %>
  </div>
</div>
<hr>
<%= f.submit "Publicar Producto", class: "btn btn-boat" %>
<% end %>
<script>

  window.handleChange = function(url, destinyId, actionId){
    var selector = document.getElementById(destinyId);
    selector.innerHTML = '';
    var newOption = document.createElement('option');
    newOption.value = ""
    newOption.text = `Select a ${destinyId}`
    selector.appendChild(newOption);

    var param = $(`#${actionId}`).val()
    debugger
    $.ajax({
      type: "GET",
      dataType: "json",
      url: `/products/${param}/${url}`,
      success: function(data){
        debugger
        var value = data.value
        for(let i =0; i < (value && value.length); i++){
          var newOption1 = document.createElement('option');
          newOption1.value = value[i]
          newOption1.text = value[i]
          selector.appendChild(newOption1);
        }
      }
    });
  }
</script>

app/views/products/_formv2.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div class="alert alert-danger">
      <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div data-controller="select" data-select-url-value="<%= subcategories_products_path %>" data-select-param-value="category">
    <div class="mb-3">
      <%= f.label :categoria, class: "form-label" %>
      <% if @categories %>
        <%= f.select :categoria, @categories, { prompt: "Select a category" }, { required: true, class: "form-select", "data-action" => "change->select#change" } %>
      <% else %>
        <% @data = Category.all.pluck(:title) %>
        <%= f.select :categoria, @data, { prompt: "Select a province" }, { required: true, class: "form-select", "data-action" => "change->select#change" } %>
      <% end %>
    </div>
    <div class="mb-3">
      <%= f.label :subcategoria, class: "form-label" %>
      <%= f.select :subcategoria, [], {}, {  required: true, class: "form-select", data: { select_target: "select" } } %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-8">
      <%= f.label :titulo, class: "form-label" %>
      <%= f.text_field :titulo, { required: true, class: "form-control"  } %>
    </div>
    <div class="col-md-2">
      <%= f.label :precio, 'Precio por dia ($)', class: "form-label" %>
      <%= f.number_field :precio, { required: true, class: "form-control", placeholder: "0.00"  } %>
    </div>
     <div class="col-md-2">
    <%= f.label :activacion, class: "form-label" %>
    <%= f.select :activacion, ['Activo', 'Desactivo'], { prompt: "" }, { required: true, class: "form-select"  } %>
  </div>
  </div>
  <br>
  <div class="mb-3">
    <%= f.label :descripcion, class: "form-label" %>
    <%= f.text_area :descripcion,{ required: true, class: "form-control"  } %>
  </div>
  <div data-controller="select" data-select-url-value="<%= districts_products_path %>" data-select-param-value="province">
    <div class="mb-3">
      <%= f.label :provincia, class: "form-label" %>
      <% if @provinces %>
        <%= f.select :provincia, @provinces, { prompt: "Select a province" }, { class: "form-select", required: true,"data-action" => "change->select#change" } %>
      <% else %>
        <% @data = Province.all.pluck(:title) %>
        <%= f.select :provincia, @data, { prompt: "Select a province" }, { class: "form-select", required: true, "data-action" => "change->select#change" } %>
      <% end %>
    </div>
    <div class="mb-3">
      <%= f.label :distrito, class: "form-label" %>
      <%= f.select :distrito, [], {}, { class: "form-select", required: true, data: { select_target: "select" } } %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= f.label :corregimiento, class: "form-label" %>
      <%= f.text_field :corregimiento, { required: true, class: "form-control"  } %>
    </div>
    <div class="col-md-4">
      <%= f.label :sector, class: "form-label" %>
      <%= f.text_field :sector,  { required: true, class: "form-control"  } %>
    </div>
    <div class="col-md-4">
      <%= f.label :marina, class: "form-label" %>
      <%= f.text_field :marina,  { required: true, class: "form-control"  } %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class="col">
      <%= f.label :photos, class: "form-label" %>
      <%= f.file_field :photos,{  multiple: true, class: 'form-control file', required: true } %>
    </div>
  </div>
  <hr>

  <%= f.submit "Guardar Producto", class: "btn btn-boat" %>
<% end %>

app/views/products/_product.html.erb
<%= link_to product_path(product) do %>
<div style="padding-bottom: 20px">
  <div class="card-trip">
    <% if product.photos[0]%>
    <img src="<%= cl_image_path product.photos[0].key, height: 300, crop: :fill %>" />
    <% end -%>
    <div class="card-trip-title" style="padding-left:16px; padding-right:16px; padding-top:16px;">
    <p><%= product.titulo %> </p>
  </div>
    <div class="card-trip-infos">
      <div>
        <p><i class="fas fa-anchor" style="color: #2078AD;"></i> <%= product.categoria %></p>
      </div>
      <p class="card-trip-pricing"> $ <%= '%.2f' % product.precio %></p>
    </div>
  </div>
</div>
<% end %>

app/views/products/districts.turbo_stream.erb
<%= turbo_stream.update @target do %>
  <%= options_for_select @districts %>
<% end  %>

app/views/products/edit.html.erb
<div class="container" style="padding-top: 100px;">
  <div style="background-color: white; padding: 30px;  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
    <br>
    <h2 style=" font-family: 'IM Fell DW Pica SC', serif;"><i class="fas fa-store" style="color: #2078AD;"></i>Editar Producto</h2>
    <hr>
    <% if current_user == @product.user  %>
    <%= render "form_update", product: @product %>
    <% elsif current_user and current_user.admin %>
    <%= form_for(@product) do |f| %>
    <% if @product.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <br>

    <div class="row">
      <div class="col-md-12">
        <%= f.label :estatus, class: "form-label" %>
        <%= f.select :estatus, ['','Valido', 'Invalido'], { prompt: " Validar producto" }, class: "form-select" %>
      </div>
    </div>
    <br>
    <hr>
    <%= f.submit "Guardar Producto", class: "btn btn-boat" %>
    <% end %>
    <% else  %>
        <br>
    <% end %>
  </div>
</div>
<br>
<br>
<br>

app/views/products/new.html.erb
<div class="container" style="padding-top: 100px;">
  <div style="background-color: white; padding: 30px;  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
    <br>
    <h2 style=" font-family: 'IM Fell DW Pica SC', serif;"><i class="fas fa-store" style="color: #2078AD;"></i>Nuevo Producto</h2>
    <hr>
    <%= render "form", product: @product %>
    <br>
    <div>
    </div>
  </div>
</div>
<br>
<br>
<br>

app/views/products/show.html.erb
<div class="container">
 <div class=" " style="padding-top: 80px; padding-bottom: 100px;">
  <br>
  <br>
  <div class="row">
   <div class="col-md-6">
    <!-- Carousel -->
    <div id="demo" class="carousel slide" data-bs-ride="carousel">

      <!-- Indicators/dots -->
      <div class="carousel-indicators">
        <% @product.photos.each_with_index do | photo, index | %>
        <% if index == 0 %>
        <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
        <% else %>
        <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
        <% end %>
        <% end %>
      </div>

      <!-- The slideshow/carousel -->
      <div class="carousel-inner">
        <% @product.photos.each_with_index do | photo, index | %>
        <% if index == 0 %>
        <div class="carousel-item active">
          <img src="<%= cl_image_path photo.key %>" alt="Los Angeles" class="d-block w-100">
        </div>
        <% else %>
        <div class="carousel-item">
          <img src="<%= cl_image_path photo.key%>" alt="Chicago" class="d-block w-100">
        </div>
        <% end %>
        <% end %>
      </div>

      <!-- Left and right controls/icons -->
      <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
        <span class="carousel-control-prev-icon"></span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
        <span class="carousel-control-next-icon"></span>
      </button>
    </div>

  </div>
  <div class="col-md-6">
    <div style="background-color: white; padding: 30px;  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">

      <h1><%= @product.titulo %></h1>
      <p><i class="fas fa-anchor"></i> Categoria: <%= @product.categoria %></p>
      <p><i class="fa-solid fa-sack-dollar"></i> Price: $<%= '%.2f' % @product.precio %></p>
      <% if @product and current_user  %>
      <%if current_user.id == @product.user.id%>

      <i class="fas fa-pencil"></i> <%= link_to "Editar", edit_product_path(@product)%> | <i class="fas fa-trash"></i> <a type="button" style='color: #0D6FED;' data-bs-toggle="modal" data-bs-target="#deleteModal">Eliminar</a>
      <%end%>
      <%end%>
      <% if current_user and current_user.admin %>
        <i class="fas fa-pencil"></i> <%= link_to "Editar", edit_product_path(@product)%> | <i class="fas fa-trash"></i> <a type="button" style='color: #0D6FED;' data-bs-toggle="modal" data-bs-target="#deleteModal">Eliminar</a>
      <% end %>
      <hr>
      <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title" id="deleteModalLabel">Eliminar <%= @product.titulo %></h4>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>Seguro que deseas eliminar este producto?</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
              <button type="button" class="btn btn-danger" style="color: white;"><%= link_to 'Eliminar', @product,data: { "turbo-method": :delete }, remote: true %></button>
            </div>
          </div>
        </div>
      </div>
      <div style="display: flex; justify-content: space-between;" data-bs-toggle="collapse" data-bs-target="#data">
        <h4 class=""><i class="fas fa-info-circle"></i> Más Informacion </h4>
        <h4><i class="fa-solid fa-chevron-down "></i></h4>
      </div>
      <div id="data" class="collapse">
        <hr>

        <p>
          <strong> <i class="fas fa-circle"></i> Tipo:</strong>
          <%= @product.subcategoria %>
        </p>
        <p>
          <strong><i class="fas fa-file-alt"></i> Description:</strong>
          <%= @product.descripcion %>
        </p>
        <p>
          <strong><i class="fa-solid fa-location"></i> Ubicacion:</strong>
          <%= @product.provincia %>, <%= @product.distrito %>
        </p>

        <p>
          <strong><i class="fa-solid fa-user"></i> Propietario:</strong>
          <%= @product.user.profile.nombre_completo %>
        </p>



      </div>
      <hr>
      <% products = [] %>
      <% current_order.order_items.each do |x| %>
      <% products.append(x.product.id)  %>
      <% end %>
      <% if current_user %>
      <% if @product.activacion === 'Activo' and @product.estatus === 'Valido' %>
      <%= form_for @order_item, remote: true  do |f|%>
      <%= f.hidden_field :product_id, :value => @product.id %>
      <div style="display: flex;">
        <div style="padding-right: 20px;">
          <p>Desde</p>
          <%= f.date_field :start_date, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control', required: true  %>
        </div>
        <div>
          <p>Hasta</p>
          <%= f.date_field :end_date, as: :date, value: f.object.try(:strftime,"%m/%d/%Y"), class: 'form-control', required: true  %>
        </div>
      </div>
      <br>
      <% if products.include? @product.id %>
      <a class="btn btn-boat" href='/baskets'><i class="fas fa-shopping-basket"></i>  Agregar</a>
      <% else %>
      <%= f.submit "Reservar", class: "btn btn-boat"%>
      <% end %>

      <% end %>
      <% else %>
      <p><i class="fas fa-info-circle"></i> Nota: </p>
      <p>Esperando Valicidacion de Administrador</p>
      <% end %>
      <% else %>
      <a class="btn btn-boat" href='/users/sign_in'><i class="fas fa-shopping-basket"></i>  Agregar</a>
      <% end %>

      <br>

    </div>
  </div>
</div>
</div>
<br>
<br>
</div>

app/views/products/states.turbo_stream.erb
<%= turbo_stream.update @target do %>
  <%= options_for_select @states %>
<% end  %>

app/views/products/subcategories.turbo_stream.erb
<%= turbo_stream.update @target do %>
  <%= options_for_select @subcategories %>
<% end  %>