config/routes.rb
Rails.application.routes.draw do
  resources :contact_messages, only: [:create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "searches#new"

  resources :receipts

  get 'baskets/show'
  resources :products do
    member do
      get :subcategories
      get :districts
      get :states
      get :sectors
      get :marinas
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :profiles
  resources :order_items
  resources :searches
  resource :baskets, only: [:show]
  devise_for :users, controllers: { registrations: "registrations" }

  get '/profile',to: 'pages#dashboard'
  get '/locations',to: 'pages#locations'
  get '/about_us',to: 'pages#about_us'
  get '/contact_us',to: 'pages#contact'
  get '/your_products', to: 'pages#your_products'
  get '/your_clients', to: 'pages#your_clients'
  get '/bocas_del_toro', to: 'pages#bocas_del_toro'
  get '/cocle', to: 'pages#cocle'
  get '/colon', to: 'pages#colon'
  get '/chiriqui', to: 'pages#chiriqui'
  get '/darien', to: 'pages#darien'
  get '/herrera', to: 'pages#herrera'
  get '/los_santos', to: 'pages#los_santos'
  get '/panama', to: 'pages#panama'
  get '/veraguas', to: 'pages#veraguas'
  get '/panama_oeste', to: 'pages#panama_oeste'
  get '/embera', to: 'pages#embera'
  get '/guna_yala', to: 'pages#guna_yala'
  get '/paguelofacil_test', to: 'pages#paguelofacil_test'
  get '/payment_method', to: 'receipts#payment_method'
  get '/check_out', to: 'receipts#payment_confirmation'
  get '/card_error', to: 'pages#card_error'
  get '/thank_you', to: 'pages#thank_you'
  get '/contact', to: 'contact_messages#contact'

  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :order
  belongs_to :user
  has_many :receipt_items
  has_one :payment_confirmation
  validates :first_name, :last_name, :email, :phone, :shipping_country, :shipping_city, :shipping_address_line_1, presence: true


  def self.payment_confirmation
    PaymentConfirmation.new(receipt_id: @receipt.id, code: DateTime.now())
  end

end

app/controllers/receipts_controller.rb
require 'net/http'
require 'json'
class ReceiptsController < ApplicationController
  before_action :set_receipt, only: %i[ show edit update destroy ]
  #skip_before_action :authenticate_user!, only: [ :payment_confirmation]
  layout false, only: [:payment_method]

  # GET /receipts or /receipts.json
  def index
    @receipts = Receipt.all
  end

  # GET /receipts/1 or /receipts/1.json
  def show

  end

  # GET /receipts/new
  def new
    if current_user.profile
      @receipt = Receipt.new
    else
      redirect_to '/profiles/new'
    end
  end

  # GET /receipts/1/edit
  def edit
    if current_user.admin
      puts 'Edit Receipt'
    else
      redirect_to '/500.html'
    end
  end

  # POST /receipts or /receipts.json
  def create
    @order = current_order
    @receipt = Receipt.new(receipt_params)
    @receipt.user = current_user
    @receipt.order = current_order
    puts @receipt.order.order_items.first.product.titulo
    @receipt.status = 'En proceso'
    puts @order.subtotal
    @receipt.price = @order.subtotal
    respond_to do |format|
      if @receipt.save
         #ReceiptMailer.with(receipt: @receipt).new_receipt_email.deliver_later
        current_order.order_items.each do |item|
          ReceiptItem.create!(product_id: item.product_id, quantity: item.quantity , receipt_id: @receipt.id,  start_date: item.start_date, end_date: item.end_date )
        end
        current_order.empty_card
        format.html { redirect_to payment_method_path(receipt_id: @receipt.id), status: :see_other}
        format.json { render :show, status: :created, location: @receipt }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receipts/1 or /receipts/1.json
  def update
    if current_user.admin
      respond_to do |format|
        if @receipt.update(receipt_params)
          if @receipt.status === ""
            @receipt.status = 'En progreso'
            @receipt.save
          end
          format.html { redirect_to receipt_url(receipt_id: @receipt.id), notice: "Receipt was successfully updated." }
          format.json { render :show, status: :ok, location: @receipt }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @receipt.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path
    end
  end

  # DELETE /receipts/1 or /receipts/1.json
  def destroy
    if current_user.admin
    @receipt.receipt_items.each do |item|
      item.destroy
    end
    @receipt.destroy

    respond_to do |format|
      format.html { redirect_to receipts_url, notice: "Receipt was successfully destroyed." }
      format.json { head :no_content }
    end
    end
  end

  def payment_method
      receipt_id = params[:receipt_id]
      # Retrieve the receipt based on the ID
      @receipt = Receipt.find(receipt_id)

      puts @receipt.id
      puts @receipt.price



      data = {
      "CCLW" => '241484758C8CB86C552834D901E37436280E767CB3974685A4905F3062CB7AAEDE40F9C17FBA47BBE3B8A052E1ED96FD09E1118C8F490DFB42E0233ACBAFBD26',
      "CMTN" => @receipt.price,
      "CDSC" => 'UBoat',
      "RETURN_URL" => "https://uboat.herokuapp.com/check_out?receipt_id=#{@receipt.id}",
      "PF_CF" => '5B7B226964223A227472616D6974654964222C226E616D654F724C6162656C223A2249642064656C205472616D697465222C2276616C7565223A2254494432333435227D5D',
      "PARM_1" => '19816201',
      "EXPIRES_IN" => 3600
      }

      puts 'Sent data'
      puts data

      postR = data.map { |key, value| "#{key}=#{value}" }.join('&')

      uri = URI('https://sandbox.paguelofacil.com/LinkDeamon.cfm')
      http = Net::HTTP.new(uri.host, uri.port)
      http.use_ssl = true

      request = Net::HTTP::Post.new(uri.path)
      request.set_form_data(data)
      response = http.request(request)
      result = response.body
      puts 'API Response: '
      puts result
      puts 'API Code Response: '
      data = JSON.parse(result)
      code = data['headerStatus']['code']
      puts code

      if code != 200
        redirect_to '/card_error'
      end

      puts data['data']['url']
      @redirect_url = "#{data['data']['url']}"

    end

    def payment_confirmation
      # Get the receipt data sent to the API
      receipt_id = params[:receipt_id]
      # Retrieve the receipt based on the ID
        @receipt = Receipt.find(receipt_id) # replace with the actual parameter name
        total_pagado = params[:TotalPagado].to_f
        fecha = Date.strptime(params[:Fecha], '%d/%m/%Y')
        hora = Time.parse(params[:Hora])
        tipo = params[:Tipo]
        oper = params[:Oper]
        usuario = params[:Usuario]
        email = params[:Email]
        estado = params[:Estado]
        razon = params[:Razon]
        cmtn = params[:CMTN].to_f
        cdsc = params[:CDSC]
        cclw = params[:CCLW]
      if @receipt.payment_confirmation
        puts 'receipt already paid'
        redirect_to '/card_error'
      else
        # Create a new PaymentConfirmation record
        if total_pagado > 0 && estado != 'Denegada'
          payment_confirmation = PaymentConfirmation.new(
            receipt: @receipt, # replace with the actual receipt object
            code: oper # replace with the appropriate key to access the code in receipt_data
          )
          respond_to do |format|
          if payment_confirmation.save
            @receipt.status = 'Pago'
            @receipt.save
            ReceiptMailer.with(receipt: @receipt).new_receipt_email.deliver_later
            format.html { redirect_to thank_you_path, status: :see_other}
            format.json { render json: { success: true, message: 'Payment confirmation created successfully' } }
          else
             format.json { render json: { success: false, message: 'Failed to create payment confirmation' }}
          end
          end
        else
          @receipt.receipt_items.each do |item|
            item.destroy
          end
          @receipt.destroy
          puts 'Error on payment'
          redirect_to '/card_error'
      end
    end
    end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipt
      @receipt = Receipt.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def receipt_params
      params.require(:receipt).permit(:first_name, :last_name, :email, :phone, :shipping_address_line_1, :shipping_address_line_2, :shipping_city, :shipping_state, :shipping_postal_code, :shipping_country, :credit_card_number, :cardholder_name, :expiration_month, :expiration_year, :cvv_code, :product_name, :quantity, :price, :subtotal, :shipping_method, :taxes, :total, :gift_message, :coupon_code, :order_notes, :status, :order_id, :user_id, :order_item_id)
    end

end

app/views/receipts/_form.html.erb
<%= simple_form_for(@receipt) do |f| %>
<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-inputs">
  <h5><i class="fas fa-user" style="color: #2078AD;"></i> Contacto</h5>
  <div class="row">
    <div class="col-md-6"><%= f.input :first_name %></div>
    <div class="col-md-6"><%= f.input :last_name %></div>
  </div>
  <div class="row">
    <div class="col-md-6"><%= f.input :email %></div>
    <div class="col-md-6"><%= f.input :phone %></div>
  </div>
  <h5><i class="fas fa-truck" style="color: #2078AD;"></i> Envio y Facturacion</h5>

  <div class="row">
   <div class="col-md-4"><%= f.input :shipping_country, as: :string%></div>
   <div class="col-md-4"><%= f.input :shipping_city, as: :string%></div>
   <div class="col-md-4"><%= f.input :shipping_postal_code, as: :string%></div>
 </div>
 <div class="row">
  <div class="col-md-12"><%= f.input :shipping_address_line_1 %></div>
</div>
<h5><i class="fas fa-align-justify" style="color: #2078AD;"></i>Nota</h5>
<%= f.input :order_notes %>

</div>
<hr>
<div class="basket-item">
  <div>
    <h4> Subtotal: <%= '%.2f' % current_order.subtotal %></h4>
    <h3> Total: <%= '%.2f' % current_order.subtotal %></h3>
  </div>
  <div>
    <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-boat'%>
    </div>
  </div>
</div>
<% end %>

app/views/receipts/_receipt.html.erb
<div id="">
<% @receipt.receipt_items.each_with_index do |item| %>
<% if item.product %>
<% if item.product.user_id === current_user.id %>
<h4>Cliente</h4>
<div class="row">
  <div class="col-md-2">
    <%= image_tag("user-boat.png", height: "100px")%>
  </div>
  <div class="col-md-5 text-start">
    <p><strong>Nombre completo:</strong> <%= @receipt.user.profile.nombre_completo %></p>
    <p><strong>Nacionalidad:</strong> <%= @receipt.user.profile.nacionalidad %></p>
  </div>
  <div class="col-md-5 text-start">
    <p><strong>Correo Electronico:</strong> <%= @receipt.user.email %></p>
    <p><strong>Telefono:</strong> <%= @receipt.user.profile.telefono %></p>
  </div>
</div>
<% end %>
<% end %>
<% end %>
<h4>Informacion de Facturacion</h4>
  <div class="row">
    <div class="col-md-6">
      <p>
        <strong>First name:</strong>
        <%= receipt.first_name %>
      </p>
    </div>
    <div class="col-md-6">
      <p>
        <strong>Last name:</strong>
        <%= receipt.last_name %>
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <p>
        <strong>Email:</strong>
        <%= receipt.email %>
      </p>
    </div>
    <div class="col-md-6">
      <p>
        <strong>Phone:</strong>
        <%= receipt.phone %>
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
     <p>
      <strong>Shipping country:</strong>
      <%= receipt.shipping_country %>
    </p>
  </div>
  <div class="col-md-4">
   <p>
    <strong>Shipping city:</strong>
    <%= receipt.shipping_city %>
  </p>
</div>
<div class="col-md-4">

 <p>
  <strong>Shipping postal code:</strong>
  <%= receipt.shipping_postal_code %>
</p>
</div>
</div>

<p>
  <strong>Shipping address:</strong>
  <%= receipt.shipping_address_line_1 %>
</p>

<p>
  <strong>Order notes:</strong>
  <%= receipt.order_notes %>
</p>
<br>
</div>
<h4>Productos</h4>
<% @receipt.receipt_items.each_with_index do |item, index| %>
<% if item.product %>
<% index += 1 %>
<div class="basket-item">
  <div>
    <h3><%= index %> - <%= item.product.titulo %> </h3>
    <p><strong>Propietario: </strong><%= item.product.user.profile.nombre_completo%></p>

    <p><strong>De:</strong> <%= item.start_date.strftime("%a, %d %b %Y")%> | <strong>Hasta:</strong> <%= item.end_date.strftime("%a, %d %b %Y")%> </p>
  </div>
  <div>
    <h2><i class="fas fa-dollar-sign" style="color: #2078AD;"></i> <%= '%.2f' % item.total %> </h2>
  </div>
</div>
<% else %>
<h2>Producto Eliminado</h2>
<% end %>
<% end %>
<hr>
<div class="basket-item">
          <div>
             <h4> Subtotal: <%= '%.2f' %  @receipt.price  %></h4>
              <h3> Total: <%= '%.2f' %  @receipt.price  %></h3>
          </div>
          <div>

            <div class="form-actions">
              <% if current_user and current_user.admin %>
         <i class="fas fa-trash"></i> <a type="button" style='color: #0D6FED;' data-bs-toggle="modal" data-bs-target="#deleteModal">Eliminar</a>
      <% end %>
      <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title" id="deleteModalLabel">Eliminar <%= @receipt.id %></h4>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>Seguro que deseas eliminar este producto?</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
              <button type="button" class="btn btn-danger" style="color: white;"><%= link_to 'Eliminar', @receipt, data: { "turbo-method": :delete }, remote: true %></button>
            </div>
          </div>
        </div>
      </div>
            </div>
          </div>
        </div>

app/views/receipts/edit.html.erb
<br>
<br>
<br>
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <div class="div" style="">
      <div style="background-color: white; padding: 30px;  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
       <h2><i class="fas fa-receipt" style="color: #2078AD;"></i> Actualizar Orden</h2>
       <hr>
       <div id="container-form" >
        <% if current_user.admin %>
        <%= simple_form_for(@receipt) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <div class="form-inputs">
          <h5><i class="fas fa-user" style="color: #2078AD;"></i> Status</h5>
          <div class="row">
            <div class="col-md-12"><%= f.input :status, :collection => ['Confirmado','Completado'], required: true  %></div>
          </div>
        <div>
          <hr>
          <div class="form-actions">
            <%= f.button :submit, class: 'btn btn-boat' %>
          </div>
        </div>
      </div>
      <% end %>
       <% end %>
      <br>
      <div>
      </div>
    </div>
  </div>
  <div class="col-md-2"></div>
</div>
</div>
</div>
<br>
<br>

app/views/receipts/index.html.erb
<br>
<br>
<div class="container">
  <div class="div" style="padding-top: 100px;">
    <div style="background-color: white; padding: 30px;  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
      <% if current_user.admin  %>
      <h2><i class="fas fa-receipt" style="color: #2078AD;"></i>Reservas</h2>
      <hr>
      <div class="table-responsive">
       <div class="table-responsive">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Nombre</th>
              <th scope="col">Total</th>
              <th scope="col">Fecha</th>
              <th scope="col">Estatus</th>
              <th scope="col"><i class="fas fa-eye"></i></th>
              <th scope="col"><i class="fas fa-pencil-alt"></i></th>
            </tr>
          </thead>

          <tbody>
            <% @receipts.each do |receipt| %>
            <tr>
              <th scope="row"><%= receipt.id %></th>
              <th scope="row"><%= receipt.first_name %> <%= receipt.last_name %></th>
              <th scope="row"><%= receipt.price %></th>
              <th scope="row"><%= receipt.created_at %></th>
              <th scope="row"><%= receipt.status %></th>
              <th scope="row"><%= link_to 'Ver', receipt %></th>
              <th scope="row"><%= link_to 'Editar', edit_receipt_path(receipt) %></th>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <br>
      <hr>
    </div>
    <% else %>
    <h2><i class="fas fa-receipt" style="color: #2078AD;"></i> Tus reservas</h2>
    <hr>
    <br>
    <div class="row">
      <% @receipts.each do |receipt| %>
      <% if receipt.payment_confirmation %>
      <% if current_user == receipt.user %>
      <div class="col-md-3">
        <div >
          <div class="" style="background-color: #2078AD;">
            <p style="color: white; margin-bottom: 0px !important; padding-left: 10px;">Reserva #<%= receipt.id %> </p>
          </div>
          <div>
            <% if current_user == receipt.user %>
            <% if receipt.receipt_items.first and receipt.receipt_items.first.product %>
            <% if receipt.receipt_items.first.product.photos[0] %>
            <div class="banner-receipt" style="background-image: url(<%= cl_image_path receipt.receipt_items.first.product.photos[0].key%>);">
            </div>
            <% end -%>
            <h3 style=""><%= receipt.receipt_items.first.product.titulo %></h3>
            <% else  %>
            <div style="background-color: #2078AD;">
            <div class="banner-receipt" style="background-image: url(<%= asset_path('8.png')%>);">
            </div>
            </div>
            <h3>Producto Eliminado</h3>
            <% end %>
            <div style="display: flex; justify-content: space-between; s">
            <p style="">$ <%= '%.2f' % receipt.price %></p>
            <p><%= receipt.created_at.strftime("%Y-%m-%d") %></p>
            </div>
            <%= link_to 'Ver', receipt, class: 'btn btn-boat' %>
            <% end %>
          </div>
          <br>
          <br>
        </div>
      </div>
      <% end %>
      <% end %>
      <% end %>
    </div>
    <hr>
    <% if  current_user %>
        <a class="btn btn-boat" href="/products"><i class="fas fa-store"></i> Ver Productos</a>
       <% end %>
    <% end %>
  </div>
</div>
</div>
<br>
<br>
<br>
<br>

app/views/receipts/new.html.erb
<br>
<br>
<br>
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <div class="div" style="">
      <div style="background-color: white; padding: 30px;  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
       <h2><i class="fas fa-receipt" style="color: #2078AD;"></i> Info. de compra</h2>
       <hr>
       <div id="container-form" >

        <%= simple_form_for(@receipt) do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

        <div class="form-inputs">
          <h5><i class="fas fa-user" style="color: #2078AD;"></i> Contacto</h5>
          <div class="row">
            <div class="col-md-6"><%= f.input :first_name, required: true %></div>
            <div class="col-md-6"><%= f.input :last_name, required: true %></div>
          </div>
          <div class="row">
            <div class="col-md-6"><%= f.input :email, required: true %></div>
            <div class="col-md-6"><%= f.input :phone, required: true %></div>
          </div>
          <h5><i class="fas fa-truck" style="color: #2078AD;"></i> Envio y Facturacion</h5>

          <div class="row">
            <div class="col-md-6"><%= f.input :shipping_country, as: :string, required: true %></div>
            <div class="col-md-6"><%= f.input :shipping_city, as: :string, required: true %></div>
          </div>
          <div class="row">
            <div class="col-md-12"><%= f.input :shipping_address_line_1, required: true %></div>
          </div>
          <h5><i class="fas fa-align-justify" style="color: #2078AD;"></i> Nota</h5>
          <%= f.input :order_notes %>
        </div>

        <hr>

        <div class="basket-item">
          <div>
            <h4> Subtotal: <%= '%.2f' % current_order.subtotal %></h4>
            <h3> Total: <%= '%.2f' % current_order.subtotal %></h3>
          </div>
          <div>
            <div class="form-actions">
              <%= button_to receipts_path, method: :post, class: 'btn btn-boat' do %>

                <i class="fa-solid fa-credit-card"></i> Pagar con Visa o Mastercard

              <% end %>
            </div>
          </div>
        </div>
        <% end %>

      </div>
    </div>
    <div class="col-md-2"></div>
  </div>
</div>
</div>
<br>
<br>

app/views/receipts/payment_confirmation.html.erb
<h1>Create Payment Confirmation</h1>

<p>Receipt ID: <%= @receipt.id %></p>

app/views/receipts/payment_method.html.erb
<script>
  window.location.href = '<%= @redirect_url %>';
</script>

app/views/receipts/show.html.erb
<br>
<br>
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">
    <div class="container" style="padding-top: 30px;">
      <div style="background-color: white; padding: 30px;  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
        <div style="display: flex; justify-content: space-between;">
        <div>
        <h2><i class="fas fa-receipt" style="color: #2078AD;"></i> Orden #0<%= @receipt.id %></h2>
      </div>
        <div>
          <h2><i class="fas fa-circle" style="color: #2078AD;"></i> Status: <%= @receipt.status %></h2>
        </div>
      </div>
        <hr>
        <%= render @receipt %>


      </div>
    </div>
  </div>
  <div class="col-md-2"></div>
</div>
<br>
<br>
<br>
<br>